#
#   ▄▄▄▄   ▓█████▄▄▄█████▓▄▄▄█████▓▓█████  ██▀███       ██████ ▓█████  ▄████▄   █    ██  ██▀███   ██▓▄▄▄█████▓▓██   ██▓
#  ▓█████▄ ▓█   ▀▓  ██▒ ▓▒▓  ██▒ ▓▒▓█   ▀ ▓██ ▒ ██▒   ▒██    ▒ ▓█   ▀ ▒██▀ ▀█   ██  ▓██▒▓██ ▒ ██▒▓██▒▓  ██▒ ▓▒ ▒██  ██▒
#  ▒██▒ ▄██▒███  ▒ ▓██░ ▒░▒ ▓██░ ▒░▒███   ▓██ ░▄█ ▒   ░ ▓██▄   ▒███   ▒▓█    ▄ ▓██  ▒██░▓██ ░▄█ ▒▒██▒▒ ▓██░ ▒░  ▒██ ██░
#  ▒██░█▀  ▒▓█  ▄░ ▓██▓ ░ ░ ▓██▓ ░ ▒▓█  ▄ ▒██▀▀█▄       ▒   ██▒▒▓█  ▄ ▒▓▓▄ ▄██▒▓▓█  ░██░▒██▀▀█▄  ░██░░ ▓██▓ ░   ░ ▐██▓░
#  ░▓█  ▀█▓░▒████▒ ▒██▒ ░   ▒██▒ ░ ░▒████▒░██▓ ▒██▒   ▒██████▒▒░▒████▒▒ ▓███▀ ░▒▒█████▓ ░██▓ ▒██▒░██░  ▒██▒ ░   ░ ██▒▓░
#  ░▒▓███▀▒░░ ▒░ ░ ▒ ░░     ▒ ░░   ░░ ▒░ ░░ ▒▓ ░▒▓░   ▒ ▒▓▒ ▒ ░░░ ▒░ ░░ ░▒ ▒  ░░▒▓▒ ▒ ▒ ░ ▒▓ ░▒▓░░▓    ▒ ░░      ██▒▒▒
#  ▒░▒   ░  ░ ░  ░   ░        ░     ░ ░  ░  ░▒ ░ ▒░   ░ ░▒  ░ ░ ░ ░  ░  ░  ▒   ░░▒░ ░ ░   ░▒ ░ ▒░ ▒ ░    ░     ▓██ ░▒░
#   ░    ░    ░    ░        ░         ░     ░░   ░    ░  ░  ░     ░   ░         ░░░ ░ ░   ░░   ░  ▒ ░  ░       ▒ ▒ ░░
#   ░         ░  ░                    ░  ░   ░              ░     ░  ░░ ░         ░        ░      ░            ░ ░
#        ░                                                            ░                                        ░ ░
#
#   Version: 1.3 | BungeeCord Version
#   Messages - en_US [English]
#
#   Wiki: https://zs0bye.gitbook.io/bettersecurity/plugins/bettersecurity
#

# ------------------
# General Messages
is_not_number: '%prefix%&cPlease enter a valid number!'
insufficient_permissions: '%prefix%&cYou don''t have enough permissions!'
update_notification: '%prefix%A new update is available! (You currently have: &c%old%&7), Download the new version &e%new%&7 from &ahttps://www.spigotmc.org/resources/bettersecurity-%E2%9C%A8-the-best-security-for-your-server.105608/'

# ------------------
# Help Command Messages
Help_Command:
  categories:
    bettersecuritybungee:
      pages:
        1:
          - ''
          - '&6 ┃ &e%version% ‑ %proxy%'
          - ''
          - '&6 ┃ &d[] &7⁼ &7Optional'
          - '&6 ┃ &c‹› &7⁼ &7Required'
          - ''
          - '&6 ┃ &f/%command% help &7‑ &eOpen this page.'
          - '&6 ┃ &f/%command% about &7‑ &eShow plug-in info.'
          - '&6 ┃ &f/%command% reload &7‑ &eReload configurations.'
          - ''
          - '&6 ┃ &7Page &e%page%&7/&e%maxpage%'
          - '&6 ┃ &e%author%'
          - ''
  placeholders:
    max_page: 'Max'
  errors:
    page_not_found: '%prefix%&cThis page was not found!'

# ------------------
# Reload Command Messages
Reload_Command:
  configurations: '%prefix%Configurations have been reloaded!'